# Generated by Django 4.2.6 on 2023-10-12 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('MiddleName', models.DateTimeField()),
                ('LastName', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DayTitle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(max_length=200)),
                ('EventStarted', models.DateTimeField()),
                ('EventEnded', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.CharField(max_length=200)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsQRApp.attendee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsQRApp.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendeeDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datestamp', models.DateTimeField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsQRApp.day')),
                ('event_attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsQRApp.eventattendee')),
            ],
        ),
    ]
