# Generated by Django 4.2.6 on 2023-10-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsQRApp', '0002_alter_attendee_lastname_alter_attendee_middlename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendeeday',
            name='datestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
