# Generated by Django 4.2.6 on 2023-10-18 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EventsQRApp", "0003_alter_eventattendeeday_datestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventattendeeday",
            name="day",
        ),
        migrations.DeleteModel(
            name="Day",
        ),
    ]
