# Generated by Django 4.2.6 on 2023-10-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EventsQRApp", "0004_remove_eventattendeeday_day_delete_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventattendeeday",
            name="day",
            field=models.IntegerField(default=0),
        ),
    ]
